server:
  port: 8000

spring:
  application:
    name: eureka-server-test

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka、
#  server:
#    retention-time-in-m-s-in-delta-queue: 0 # 客户端保持增量信息缓存的时间，从而保证不会丢失这些信息，单位为毫秒，默认为3 * 60 * 1000
#  server:
#    use-read-only-response-cache: true # 使用只读的响应缓存
#  instance:
#    registry:
#      expected-number-of-clients-sending-renews: 1 # 期望的发送续约心跳的客户端数量，默认是1

#  server:
#    expected-client-renewal-interval-seconds: 30 # 期望的客户端发送续约心跳的间隔时间，默认是30s
#    renewal-percent-threshold: 0.85 # 自我保护机制开启的阈值因子，默认是0.85